---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev-pizza-castle
  namespace: flux-system
spec:
  healthChecks:
    - kind: Deployment
      name: dev-pizza-castle-menu-service
      namespace: dev-pizza-castle
    - kind: Deployment
      name: dev-pizza-castle-ordering-service
      namespace: dev-pizza-castle
    - kind: Deployment
      name: dev-pizza-castle-web
      namespace: dev-pizza-castle
  interval: 1m0s
  path: ./kubernetes/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: pizza-castle-infrastructure
  timeout: 2m0s
  validation: client
