apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: pizza-castle-images
  namespace: flux-system
spec:
  images:
    - name: kajendranalagaratnam/pizza-castle-web
      interval: 1m0s
    - name: gayankanishka/pizza-castle-menu-service
      interval: 1m0s
    - name: gayankanishka/pizza-castle-ordering-service
      interval: 1m0s
