apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: ordering-service-image-repository
  namespace: flux-system
spec:
  image: gayankanishka/pizza-castle-ordering-service
  interval: 1m0s
