---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: pizza-castle-prod
  namespace: flux-system
spec:
  healthChecks:
    - kind: Deployment
      name: pizza-castle-menu-service
      namespace: pizza-castle-prod
    - kind: Deployment
      name: pizza-castle-ordering-service
      namespace: pizza-castle-prod
  interval: 1m0s
  path: ./kubernetes/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: pizza-castle-infrastructure
  timeout: 2m0s
  validation: client
