apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ordering-service-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ordering-service-image-repository
  filterTags:
    pattern: '^staging-[a-fA-F0-9]+-(?P<ts>[1-9][0-9]*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
